salesforce/force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Car Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce/force-app/main/default/objects/Car_Reservation__c/Car_Reservation__c.object-meta.xml
<CustomObject>
    <label>Car Reservation</label>
    <nameField>
        <displayFormat>res#{0}</displayFormat>
        <label>Car Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforce/force-app/main/default/objects/Car_Reservation__c/fields/Car__c.field-meta.xml
<CustomField>
    <fullName>Car__c</fullName>
    <label>Car</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Car Reservations</relationshipLabel>
    <relationshipName>Car_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

salesforce/force-app/main/default/objects/Car_Reservation__c/fields/Reservation_End__c.field-meta.xml
<CustomField>
    <fullName>Reservation_End__c</fullName>
    <label>Reservation End</label>
    <type>Date</type>
</CustomField>

salesforce/force-app/main/default/objects/Car_Reservation__c/fields/Reservation_Start__c.field-meta.xml
<CustomField>
    <fullName>Reservation_Start__c</fullName>
    <label>Reservation Start</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

salesforce/force-app/main/default/classes/RentCar.cls
public with sharing class RentCar {
    @AuraEnabled
    public static void rentThisCar(String carId, Date startDate, Date endDate){
        //create car_Reservation__c with Car__c set to carId
        Date startD = Date.valueOf(startDate);
        Date endD = Date.valueOf(endDate);
        Car_Reservation__c res;
        if (Schema.sObjectType.Car_Reservation__c.isCreateable()) {
            res= new Car_Reservation__c(
                Reservation_Start__c = startD,
                Reservation_End__c = endD,
                Car__c = carId);
         } 
        try{
            insert res;
        }catch(DMLException err){
            System.debug(err);
        }
    }

    @AuraEnabled
    public static List<Date> getDatesAvailable(String carId){
        List<Date> datesAvailable = new List<Date>();
        //return dates this car is not reserved
        if (String.isEmpty(carId)){
            datesAvailable.add(Date.today().addDays(1));
            return datesAvailable;
        }else{
            datesAvailable = nextThirtyDays();
            for(Car_Reservation__c cr:[
                                SELECT Id, Reservation_Start__c, Reservation_End__c
                                FROM Car_Reservation__c
                                WHERE Car__c =:carId]){
                removeDateRange(datesAvailable,cr.Reservation_Start__c,cr.Reservation_End__c);
                //remove dates from datesComing that lie between reservation start and end dates
            }
        }
        if(datesAvailable.size() == 0){
            datesAvailable.add(Date.today());
        }
        return datesAvailable;
    }
    static void removeDateRange(List<Date> available, Date startRes, Date endRes ){
        for( Integer i = 0 ; i < startRes.daysBetween(endRes) ; i++){
            Date unavailableDate = startRes.addDays(i);
            Integer indexOf = available.indexOf(unavailableDate);
            if(indexOf != -1){
                available.remove(indexOf);
            }
        }
    }
    
    static List<Date> nextThirtyDays(){
        List<Date> datesComing = new List<Date>();
        Date today = Date.today();

        for(Integer i = 0 ; i < 30 ; i++){
            datesComing.add(today.addDays(i));
        }
        return datesComing;
    }
    

}